---
upload_path: "/site/static/images/uploads/:year:/:month:"
frontmatter_file_url_template: "/images/uploads/:year:/:month:"
body_file_url_template: "/images/uploads/:year:/:month:"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections: 
version: 0.25.1
