---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections: 
upload_dir: site/static/images/uploads
public_path: "/images/uploads"
front_matter_path: "/images/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
version: 0.25.1
