staticDir = ["static"]
baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "RAAR"
paginate = 10
paginatePath = "page"

[[menu.main]]
    name = "obiblanche"
    identifier = "obiblanche"
    url = "/obiblanche/"
[[menu.main]]
    name = "obizine"
    identifier = "obizine"
    url = "/obizine/"
[[menu.main]]
    name = "label"
    identifier = "label"
    url = "/label/"
[[menu.main]]
    name = "releases"
    identifier = "releases"
    url = "/releases/"
[[menu.main]]
    name = "news archives"
    identifier = "archives"
    url = "/tags/"

[taxonomies]
  tag = "tags"
